theme                  : "minimal-mistakes-jekyll"
minimal_mistakes_skin    : "dirt" #"air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

title: Havanafrog
logo: /assets/img/logo.jpeg
email: pierrot0819@ajou.ac.kr
description: Probablity & stostachics
show_downloads: false
color-scheme: white
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: Scholar
    icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path d="M5.242 13.769L0 9.5L12 0l12 9.5l-5.242 4.269C17.548 11.249 14.978 9.5 12 9.5c-2.977 0-5.548 1.748-6.758 4.269zM12 10a7 7 0 1 0 0 14a7 7 0 0 0 0-14z" fill="currentColor"/></svg>
    link: https://dcoll.ajou.ac.kr/dcollection/srch/srchDetail/000000031849?navigationSize=10&query=%2B%28%28subject%3A%22optimal+scaling%22%29%29&pageSize=10&insCode=241038&searchWhere1=subject&sortDir=desc&searchTotalCount=0&searchOption=em&pageNum=1&rows=10&searthTotalPage=0&treePageNum=1&sortField=score&start=0&ajax=false&searchText=%5B%EC%A3%BC%EC%A0%9C%EC%96%B4%3A+Optimal+scaling%5D&searchKeyWord1=+Optimal+scaling
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/havanafrog
  - name: Blog
    icon: <i class="fa-solid fa-pen"></i>
    link: https://havanafrog.github.io
  - name: Project Repository
    icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 16 16"><g fill="currentColor"><path d="M12.643 15C13.979 15 15 13.845 15 12.5V5H1v7.5C1 13.845 2.021 15 3.357 15h9.286zM5.5 7h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1zM.8 1a.8.8 0 0 0-.8.8V3a.8.8 0 0 0 .8.8h14.4A.8.8 0 0 0 16 3V1.8a.8.8 0 0 0-.8-.8H.8z"/></g></svg>
    link: https://github.com/havanafrog/Project

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      toc: true
      comments: true
      share: true
      related: true
      read_time: false
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
